name: team.adler.cx product CI/CD

on:
  push:
    branches: product
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js (v20.x)
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Build and Export project
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build:publish

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Publish to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm ${{ secrets.AWS_S3_BUCKET_NAME }} --recursive
          aws s3 cp --recursive --region ${{ secrets.AWS_REGION }} ./out ${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: Invalidate Cloudfront Cache
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws cloudfront create-invalidation --distribution-id E8XK3OG1NOZNP --paths "/*"
